export const CITY_CHOSED_BY_USER = 'CITY_CHOSED_BY_USER';
export type CITY_CHOSED_BY_USER = typeof CITY_CHOSED_BY_USER;

export const CITY_CHOSED_BY_COMPUTER = 'CITY_CHOSED_BY_COMPUTER';
export type CITY_CHOSED_BY_COMPUTER = typeof CITY_CHOSED_BY_COMPUTER;

export const CURRENT_SESSION_CLEARED = 'CURRENT_SESSION_CLEARED';
export type CURRENT_SESSION_CLEARED = typeof CURRENT_SESSION_CLEARED;

export const GAME_STARTED = 'GAME_STARTED';
export type GAME_STARTED = typeof GAME_STARTED;

export const GAME_FINISHED = 'GAME_FINISHED';
export type GAME_FINISHED = typeof GAME_FINISHED;
